openapi: 3.0.0
info:
  title: Authentication API
  description: API for user authentication and profile management
  version: 1.0.0
paths:
  /api/auth/signup:
    post:
      summary: Register a new user with background information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - software_background
                - hardware_background
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: User's password
                name:
                  type: string
                  description: User's display name (optional)
                software_background:
                  type: string
                  enum: [Beginner, Frontend, Backend, AI]
                  description: User's software experience level
                hardware_background:
                  type: string
                  enum: [Low-end PC, Mid-range, High-end, GPU]
                  description: User's hardware experience level
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Invalid input data
        '409':
          description: Email already exists
  /api/auth/signin:
    post:
      summary: Sign in an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: User successfully signed in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Invalid credentials
  /api/auth/profile:
    get:
      summary: Get current user's profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized
    put:
      summary: Update user's profile including background information
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User's display name
                software_background:
                  type: string
                  enum: [Beginner, Frontend, Backend, AI]
                  description: User's software experience level
                hardware_background:
                  type: string
                  enum: [Low-end PC, Mid-range, High-end, GPU]
                  description: User's hardware experience level
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
        email:
          type: string
          format: email
        name:
          type: string
        software_background:
          type: string
          enum: [Beginner, Frontend, Backend, AI]
        hardware_background:
          type: string
          enum: [Low-end PC, Mid-range, High-end, GPU]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        background_updated_at:
          type: string
          format: date-time